### ISSUE TITLE
Wrong output of module info

### ISSUE THREAD

**Issue by rikvdkleij** [mvoidex/hsdev#75]
`hsdev module -m Control.Lens  --package lens` gives as:
```
{
        "id": {
          "name": "&",
          "module": {
            "location": {
              "dirs": [
                "/Users/rik/.stack/programs/x86_64-osx/ghc-8.2.2/lib/ghc-8.2.2/base-4.10.1.0"
              ],
              "name": "Data.Function",
              "package": "base-4.10.1.0"
            },
            "name": "Data.Function"
          }
        },
        "info": {
          "what": "function",
          "type": "a -> (a -> b) -> b"
        }
      },
 {
        "id": {
          "name": "iat",
          "module": {
            "location": {
              "dirs": [
                "/Users/rik/.stack/snapshots/x86_64-osx/lts-10.0/8.2.2/lib/x86_64-osx-ghc-8.2.2/lens-4.15.4-GmKqEk0X9J2SBrs0I2AgZ"
              ],
              "name": "Control.Lens.At",
              "package": "lens-4.15.4"
            },
            "name": "Control.Lens.At"
          }
        },
        "info": {
          "what": "function",
          "type": "At m => Index m -> IndexedLens' (Index m) m (Maybe (IxValue m))"
        }
      },
.......
```

I expect only identifiers of `lens` package.

The `&` operator exists in `base` and `lens`.

**Comment by mvoidex** [comment]
Should be fixed now.

**Comment by rikvdkleij** [comment]
Thanks!

**Comment by rikvdkleij** [comment]
I have installed version `0.3.1.0` but I still have this problem.

**Comment by mvoidex** [comment]
Could you describe steps to reproduce on clean hsdev run?
```
hsdev start
hsdev scan --cabal
hsdev module -m 'Control.Lens' --package lens | json | % { $_.id.name }
```
yield only `Control.Lens` module in my case

**Comment by mvoidex** [comment]
This output is correct
`hsdev module` returns modules with theirs exports, and `Control.Lens` reexports `Data.Function.&`

**Comment by rikvdkleij** [comment]
Okay, I see.
